version: "3.8" 

services: 
    api: 
        build:  
            dockerfile: Dockerfile
            context: ./api
        volumes: 
            - ./api:/dalba-de/src/app
            - /dalba-de/src/app/node_modules
        command: npm run start:dev
        depends_on:
            - postgres
        environment:
            DATABASE_URL: postgres://user:password@postgres:5432/db
            PORT: 3000
        ports: 
            - 3000:3000

    chatroom:
        build:
            dockerfile: Dockerfile
            context: ./chatroom
            target: development
        command: npm run start
        volumes: 
            - ./chatroom:/dalba-de/chatroom/src/app
            - /dalba-de/chatroom/src/app/node_modules
        ports: 
            - 4200:4200
        links:
            - api

    postgres:
        image: postgres:10.4
        environment: 
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: db
        ports:
            - 5432:5432

    postgres_admin:
        image: adminer
        depends_on:
            - postgres
        restart: always
        ports:
            - 8080:8080